a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))
print()

print("Addition of a and b is: ", (a+b))
print("Subtraction of a and b is: ", (a-b))
print("Multiplication of a and b is: ", (a*b))
print("Division of a and b is: ", (a/b))
print("Modulo of a and b is: ", (a%b))
print("Floor Division of a and b is: ", (a//b))
print("Exponentiation of a and b is: ", (a**b))